#!/usr/bin/env php
<?php
defined('VENDOR_PATH') or define('VENDOR_PATH', __DIR__ . '/../../');
defined('VENDOR_SERVER_PATH') or define('VENDOR_SERVER_PATH', __DIR__);
defined('APP_SERVER_PATH') or define('APP_SERVER_PATH', __DIR__ . '/../../../service');

require VENDOR_PATH . '/autoload.php';

// 配置文件
$config = require APP_SERVER_PATH . '/config/config.php';
$app = new \newx\server\base\Command($config, $argv);
$app->run();